### ISSUE TITLE
发现一个点击图片保存的问题（bug？）

### ISSUE THREAD

**Issue by superwoods** [brucevanfdm/WeChatMeiZhi#1]
## 问题:

看图说话：

![2016-10-11 13 24 39](https://cloud.githubusercontent.com/assets/7624198/19259672/5f04a500-8fb6-11e6-8828-7d352b5fcf79.png)

点击确定之后会一直在下载

猜测可能是因为 `wx.downloadFile()` 还不能在目前的微信开发工具中正常工作？
## TIPS：

我可以吐槽吗？。。。。demo的妹纸不够味道啊！哼哼哼

**Comment by bruc3van** [comment]
保存文件这里我也不知道怎么回事，也按照官方的文档写了。

更新：官方IDE更新后可以保存了！

**Comment by liujians** [comment]
downloadFile用IDE貌似看不到效果，类似的还有很多API在IDE都看不到效果，我也在我的开源项目中尝试

更新：官方IDE更新后可以保存了！

**Comment by superwoods** [comment]
嗯 确实是 v0.9 内测版的问题。。。

另外，v0.10更新之后，今天发现下拉刷新模块  `onPullDownRefresh: function(){ }` 根本无法通过 `app.json` 中的配置
`"enablePullDownRefresh": false` 关闭，这个东西完全不生效. 

唯一的关闭方法就是pages的页面控制js 不加 ``onPullDownRefresh: function(){ }`

同时，我的项目可用，但同事的项目就不生效，然后把我的项目clone 给他，他没有更改任何代码，他的项目就可以使用 `onPullDownRefresh` 了。。。。我们花了半小时找原因，但毫无收获。

感觉这个坑略大

**Comment by superwoods** [comment]
反正问题解决了。。。我Close了 讨论可以私信 email
