### ISSUE TITLE
您好，请教下API的问题。

### ISSUE THREAD

**Issue by BeijiYang** [brucevanfdm/WeChatMeiZhi#3]
请问将“福利”转为“%E7%A6%8F%E5%88%A9”，后者这属于什么码？
ps 测试时这个链接报错了，虽然点击它能正常返回数据。

**Comment by BeijiYang** [comment]
发现报错是因为，有APPID后需要后台设置域名的。

**Comment by bruc3van** [comment]
URLEncode 转成UTF-8编码

**Comment by ontheway1215** [comment]
请问一下合法域名纠错怎么解决啊？
