### ISSUE TITLE
你这个项目我下载下来运行就报错了

### ISSUE THREAD

**Issue by JremeryHe** [brucevanfdm/WeChatMeiZhi#4]
onLoad
asdebug.js:1 Thu May 25 2017 11:23:04 GMT+0800 (中国标准时间) 合法域名校验出错
asdebug.js:1 如若已经在管理后台更新域名配置，请刷新项目配置后重新编译项目，操作路径：“项目-配置信息-刷新”
asdebug.js:1  http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1 不在以下合法域名列表中，请参考文档：https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.htmlr @ asdebug.js:1v @ asdebug.js:1a @ asdebug.js:1o @ WAService.js:4u @ WAService.js:4request @ WAService.js:3(anonymous function) @ WAService.js:4requestData @ index.js [sm]:68onLoad @ index.js [sm]:39(anonymous function) @ WAService.js:7A @ WAService.js:7O @ WAService.js:7j @ WAService.js:7(anonymous function) @ WAService.js:7(anonymous function) @ WAService.js:7(anonymous function) @ WAService.js:4(anonymous function) @ WAService.js:4(anonymous function) @ WAService.js:4(anonymous function) @ asdebug.js:1n.emit @ asdebug.js:1r @ asdebug.js:1g @ asdebug.js:1(anonymous function) @ asdebug.js:1
asdebug.js:1 Array[0]
VM97:1 Thu May 25 2017 11:23:04 GMT+0800 (中国标准时间) WXML Runtime warning
VM97:2 ./pages/index/index.wxml
VM97:3  Now you can provide attr "wx:key" for a "wx:for" to improve performance.
  2 | <view>
  3 | 
> 4 |   <view class= "card" wx:for = "{{items}}">
    |    ^
  5 |   
  6 |     <view  data-url="{{item.url}}" bindtap = "onItemClick">
  7 |        <image class= "image" mode="aspectFill" src="{{item.url}}"/>

**Comment by JremeryHe** [comment]
asdebug.js:1  http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1 不在以下合法域名列表中，请参考文档：https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.html

**Comment by johanazhu** [comment]
我也是这个问题，解决了吗？
asdebug.js:1  https://ws1.sinaimg.cn/large/610dc034ly1fgj7jho031j20u011itci.jpg 不在以下合法域名列表中，请参考文档：https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.html

**Comment by johanazhu** [comment]
楼上那位，你在微信小程序里的设置——服务器域名里加“ https://gank.io”，并把“ http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1”，改为“ https://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1”
